import { builder } from "../builder"
import "./address"
import "./admin"
import "./credit-card"
import "./custom-date"
import "./date-creator"
import "./date-itinerary"
import "./date-stop"
import "./date-suggestion"
import "./default-guest"
import "./drafts"
import "./error"
import "./favorite"
import "./free-date"
import "./free-date-list"
import "./free-date-views"
import "./image"
import "./location"
import "./mixpanel"
import "./pagination"
import "./planned-date"
import "./role"
import "./tag"
import "./tastemaker"
import "./tastemaker-preference"
import "./travel"
import "./user"
import "./user-profile"

export const schema = builder.toSchema()
