import { builder } from "../builder"
import "./address"
import "./admin"
import "./categorized-date-list"
// import "./credit-card"
// import "./custom-date"
import "./date-creator"
import "./date-itinerary"
import "./date-suggestion"
import "./default-guest"
import "./drafts"
import "./error"
import "./favorite"
import "./free-date"
import "./free-date-variation"
import "./free-date-views"
import "./image"
import "./location"
import "./mixpanel"
import "./ordered-date-stop"
import "./pagination"
import "./planned-date"
import "./role"
import "./special-offer"
import "./tag"
import "./tastemaker"
import "./tastemaker-preference"
import "./travel"
import "./user"
import "./user-profile"

export const schema = builder.toSchema()
